### ISSUE TITLE
Tauri Record using Opencv --- Specifically Setting Record window for preview of camera.

### ISSUE THREAD

**Issue by deondreE** [Mumble-Tech/Mumble#18]
**Describe the bug**
The bug is simple, in the case of recording the code defines a window. The window currently being used is created on run-time, but using the window is not linked to the tauri front-end. This can probably be fixed using https://tauri.app/blog/2022/09/19/tauri-egui-0-1/

# CODE
![code](https://user-images.githubusercontent.com/67658523/198328670-a7de3a54-71e6-4841-9c94-eaf2166cd75a.png)

## Problem 
<img width="517" alt="Screenshot 2022-10-27 at 10 15 13 AM" src="https://user-images.githubusercontent.com/67658523/198329436-4d0045eb-6378-4357-9a7d-61da7ed7961b.png">

**Comment by MumbleLLC** [comment]
Need to figure out a better way to get the content of the camera from the user
