### ISSUE TITLE
Font should be change from Italic to Bold in Navbar.

### ISSUE THREAD

**Issue by Yasir761** [Mumble-Tech/Mumble#49]
**Is your feature request related to a problem? Please describe.**
I guess Navbar elements should be in Bold, it may be good for the UI experience.

**Describe the solution you'd like**
I would like to change all unnecessary Italic fonts to bold.

**Describe alternatives you've considered**
![Capture12](https://user-images.githubusercontent.com/74600745/218755478-3647535a-5795-40e1-a909-1552af5378ca.PNG)

**Additional context**

**Comment by Yasir761** [comment]
I would like to work on this.

**Comment by deondreE** [comment]
This is awesome I did end up changing the whole design I will put the new design here would love feedback and of course you can work on this! Excited to have you!

**Comment by Yasir761** [comment]
Thank You @deondreE

**Comment by deondreE** [comment]
This now becomes no longer aplicable; If you would like to fix some things on the new landing page; but the conversion is no longer nessisary. @Yasir761
